export const IngredientsList = [
    '7-up',
    '151 proof rum',
    'Absinthe',
    'Absolut citron',
    'Absolut Kurant',
    'Absolut Peppar',
    'Absolut Vodka',
    'Advocaat',
    'Aejo Rum',
    'Aftershock',
    'Agave Syrup',
    'Ale',
    'Allspice Dram',
    'Allspice',
    'Almond Extract',
    'Almond Flavoring',
    'Almond',
    'Amaretto',
    'Angelica Root',
    'Angostura Bitters',
    'Anis',
    'Anise',
    'Anisette',
    'Aperol',
    'Apfelkorn',
    'Apple Brandy',
    'Apple Cider',
    'Apple Juice',
    'Apple Schnapps',
    'Apple',
    'Applejack',
    'Apricot Brandy',
    'Apricot Nectar',
    'Apricot',
    'Aquavit',
    'Arrack',
    'Asafoetida',
    'Averna',
    'Añejo Rum',
    'Bacardi Limon',
    'Bacardi',
    'Baileys Irish Cream',
    'Banana Liqueur',
    'Banana Rum',
    'Banana Syrup',
    'Banana',
    'Barenjager',
    'Basil',
    'Beef Stock',
    'Beer',
    'Benedictine',
    'Berries',
    'Bitter lemon',
    'Bitters',
    'Black Pepper',
    'Black Rum',
    'Black Sambuca',
    'Blackberries',
    'Blackberry Brandy',
    'Blackberry Schnapps',
    'Blackcurrant Cordial',
    'Blackcurrant Schnapps',
    'Blackcurrant Squash',
    'Blackstrap rum',
    'Blended Scotch',
    'Blended Whiskey',
    'Blue Curacao',
    'Blue Maui',
    'Blueberries',
    'Blueberry Schnapps',
    'Bourbon',
    'Brandy',
    'Brown Sugar',
    'Butter',
    'Butterscotch Schnapps',
    'Cachaca',
    'Calvados',
    'Campari',
    'Canadian Whisky',
    'Candy',
    'Cantaloupe',
    'Caramel Coloring',
    'Caramel Sauce',
    'Carbonated Soft Drink',
    'Carbonated Water',
    'Cardamom',
    'Cayenne Pepper',
    'Celery Salt',
    'Celery',
    'Chambord Raspberry Liqueur',
    'Champagne',
    'Chareau',
    'Cherries',
    'Cherry Brandy',
    'Cherry Cola',
    'Cherry Grenadine',
    'Cherry Heering',
    'Cherry Juice',
    'Cherry Liqueur',
    'Cherry',
    'Chocolate Ice-cream',
    'Chocolate Liqueur',
    'Chocolate Milk',
    'Chocolate Sauce',
    'Chocolate Syrup',
    'Chocolate',
    'Cider',
    'Cinnamon Schnapps',
    'Cinnamon Whisky',
    'Cinnamon',
    'Citrus Vodka',
    'Clamato Juice',
    'Cloves',
    'Club Soda',
    'Coca-Cola',
    'Cocchi Americano',
    'Cocktail Onion',
    'Cocoa Powder',
    'Coconut Cream',
    'Coconut Liqueur',
    'Coconut Milk',
    'Coconut Rum',
    'Coconut Syrup',
    'Coffee Brandy',
    'Coffee Liqueur',
    'Coffee',
    'Cognac',
    'Cointreau',
    'Cola',
    'Cold Water',
    'Condensed Milk',
    'Coriander',
    'Corn Syrup',
    'Cornstarch',
    'Corona',
    'Cranberries',
    'Cranberry Juice',
    'Cranberry Liqueur',
    'Cranberry Vodka',
    'Cream of Coconut',
    'Cream Sherry',
    'Cream Soda',
    'Cream',
    'Creme De Almond',
    'Creme De Banane',
    'Creme De Cacao',
    'Creme De Cassis',
    'Creme de Mure',
    'Creme De Noyaux',
    'Creme de Violette',
    'Creme Fraiche',
    'Crown Royal',
    'Crystal Light',
    'Cucumber',
    'Cumin Powder',
    'Cumin Seed',
    'Curacao',
    'Cynar',
    'Daiquiri Mix',
    'Dark Chocolate',
    'Dark Creme De Cacao',
    'Dark Rum',
    'Dark Soy Sauce',
    'Demerara Sugar',
    'Diet Coke',
    'Dr. Pepper',
    'Drambuie',
    'Dried Oregano',
    'Dry Curacao',
    'Dry Vermouth',
    'Dubonnet Blanc',
    'Dubonnet Rouge',
    'Egg White',
    'Egg Yolk',
    'Egg',
    'Eggnog',
    'Elderflower cordial',
    'Erin Cream',
    'Espresso',
    'Everclear',
    'Falernum',
    'Fanta',
    'Fennel Seeds',
    'Fernet-Branca',
    'Figs',
    'Firewater',
    'Flaked Almonds',
    'Food Coloring',
    'Forbidden Fruit',
    'Frangelico',
    'Fresca',
    'Fresh Basil',
    'Fresh Lemon Juice',
    'Fresh Lime Juice',
    'Fresh Mint',
    'Fruit Juice',
    'Fruit Punch',
    'Fruit',
    'Galliano',
    'Garlic Sauce',
    'Gatorade',
    'Gin',
    'Ginger Ale',
    'Ginger Beer',
    'Ginger Syrup',
    'Ginger',
    'Glycerine',
    'Godiva Liqueur',
    'Gold rum',
    'Gold Tequila',
    'Goldschlager',
    'Grain Alcohol',
    'Grand Marnier',
    'Granulated Sugar',
    'Grape juice',
    'Grape soda',
    'Grapefruit Juice',
    'Grapes',
    'Green Chartreuse',
    'Green Creme de Menthe',
    'Green Ginger Wine',
    'Green Olives',
    'Grenadine',
    'Ground Ginger',
    'Guava juice',
    'Guinness stout',
    'Guinness',
    'Habanero Peppers',
    'Half-and-half',
    'Hawaiian punch',
    'Hazelnut liqueur',
    'Heavy cream',
    'Honey syrup',
    'Honey',
    'Hooch',
    'Hot Chocolate',
    'Hot Damn',
    'Hot Sauce',
    'Hpnotiq',
    'Ice',
    'Ice-Cream',
    'Iced tea',
    'Ilegal Joven mezcal',
    'Irish cream',
    'Irish Whiskey',
    'Islay single malt Scotch',
    'Jack Daniels',
    'Jagermeister',
    'Jello',
    'Jelly',
    'Jim Beam',
    'Johnnie Walker',
    'Kahlua',
    'Key Largo Schnapps',
    'Kirschwasser',
    'Kiwi liqueur',
    'Kiwi',
    'Kool-Aid',
    'Kummel',
    'Lager',
    'Lavender',
    'Lemon Juice',
    'Lemon Peel',
    'Lemon soda',
    'Lemon vodka',
    'lemon',
    'Lemon-lime soda',
    'lemon-lime',
    'Lemonade',
    'Licorice Root',
    'Light Cream',
    'Light Rum',
    'Lillet Blanc',
    'Lillet',
    'Lime juice cordial',
    'Lime Juice',
    'Lime liqueur',
    'Lime Peel',
    'Lime vodka',
    'Lime',
    'Limeade',
    'Madeira',
    'Malibu Rum',
    'Mandarin',
    'Mandarine napoleon',
    'Mango',
    'Maple syrup',
    'Maraschino cherry juice',
    'Maraschino Cherry',
    'Maraschino Liqueur',
    'Margarita mix',
    'Marjoram leaves',
    'Marshmallows',
    'Martini Bianco',
    'Martini Extra Dry',
    'Martini Rosso',
    'Maui',
    'Melon Liqueur',
    'Melon Vodka',
    'Mezcal',
    'Midori Melon Liqueur',
    'Midori',
    'Milk',
    'Mini-snickers bars',
    'Mint syrup',
    'Mint',
    'Mountain Dew',
    'Nocino',
    'Nutmeg',
    'Olive Brine',
    'Olive Oil',
    'Olive',
    'Onion',
    'Orange Bitters',
    'Orange Curacao',
    'Orange Juice',
    'Orange liqueur',
    'Orange Peel',
    'Orange rum',
    'Orange Slice',
    'Orange Soda',
    'Orange spiral',
    'Orange vodka',
    'Orange',
    'Oreo cookie',
    'Orgeat Syrup',
    'Ouzo',
    'Oyster Sauce',
    'Papaya juice',
    'Papaya',
    'Parfait amour',
    'Passion fruit juice',
    'Passion fruit syrup',
    'Passoa',
    'Peach Bitters',
    'Peach brandy',
    'Peach juice',
    'Peach liqueur',
    'Peach Nectar',
    'Peach Schnapps',
    'Peach Vodka',
    'Peach',
    'Peachtree schnapps',
    'Peanut Oil',
    'Pepper',
    'Peppermint extract',
    'Peppermint Schnapps',
    'Pepsi Cola',
    'Pernod',
    'Peychaud bitters',
    'Pina colada mix',
    'Pineapple Juice',
    'Pineapple rum',
    'Pineapple Syrup',
    'Pineapple vodka',
    'Pineapple',
    'Pineapple-orange-banana juice',
    'Pink lemonade',
    'Pisang Ambon',
    'Pisco',
    'Plain Chocolate',
    'Plain Flour',
    'Plums',
    'Pomegranate juice',
    'Port',
    'Powdered Sugar',
    'Prosecco',
    'Purple passion',
    'Raisins',
    'Ramazzotti',
    'Raspberry cordial',
    'Raspberry Jam',
    'Raspberry Juice',
    'Raspberry Liqueur',
    'Raspberry schnapps',
    'Raspberry syrup',
    'Raspberry Vodka',
    'Red Bull',
    'Red Chile Flakes',
    'Red Chili Flakes',
    'Red Hot Chili Flakes',
    'Red Wine',
    'Rhubarb',
    'Ricard',
    'Rock Salt',
    'Root beer schnapps',
    'Root beer',
    'Rosemary Syrup',
    'Rosemary',
    'Roses sweetened lime juice',
    'Rosewater',
    'Rosso Vermouth',
    'Rum',
    'Rumple Minze',
    'Rye Whiskey',
    'Sake',
    'Salt',
    'Salted Chocolate',
    'Sambuca',
    'Sarsaparilla',
    'Schnapps',
    'Schweppes Lemon',
    'Schweppes Russchian',
    'Scotch',
    'Sherbet',
    'Sherry',
    'Singani',
    'Sirup of roses',
    'Sloe Gin',
    'Soda Water',
    'Sour Apple Pucker',
    'Sour Mix',
    'Southern Comfort',
    'Soy Milk',
    'Soy Sauce',
    'Soya Milk',
    'Soya Sauce',
    'Spiced Rum',
    'Sprite',
    'Squeezed Orange',
    'Squirt',
    'St. Germain',
    'Strawberries',
    'Strawberry juice',
    'Strawberry liqueur',
    'Strawberry Schnapps',
    'Strawberry syrup',
    'Sugar Syrup',
    'Sugar',
    'Sunny delight',
    'Surge',
    'Swedish punsch',
    'Sweet and Sour',
    'Sweet Cream',
    'Sweet Vermouth',
    'Tabasco Sauce',
    'Tang',
    'Tawny port',
    'Tea',
    'Tennessee whiskey',
    'Tequila rose',
    'Tequila',
    'Thyme',
    'Tia Maria',
    'Tomato Juice',
    'Tomato',
    'Tonic Water',
    'Triple Sec',
    'Tropicana',
    'Tuaca',
    'Vanilla extract',
    'Vanilla Ice-Cream',
    'Vanilla liqueur',
    'Vanilla schnapps',
    'Vanilla syrup',
    'Vanilla vodka',
    'Vanilla',
    'Vermouth',
    'Vinegar',
    'Vodka',
    'Water',
    'Watermelon schnapps',
    'Watermelon',
    'Whipped Cream',
    'Whipping Cream',
    'Whiskey',
    'Whisky',
    'White chocolate liqueur',
    'White Creme de Menthe',
    'White grape juice',
    'White port',
    'White Rum',
    'White Vermouth',
    'White Vinegar',
    'White Wine',
    'Wild Turkey',
    'Wildberry schnapps',
    'Wine',
    'Worcestershire Sauce',
    'Wormwood',
    'Yeast',
    'Yellow Chartreuse',
    'Yoghurt',
    'Yukon Jack',
    'Zima'
];
